Add backup and restore feature
0xPolygon/polygon-edge-docs pull request #47
Opened 2022-01-04 07:36 UTC by Kourin1996

This PR adds the description of backup and restore added in https://github.com/0xPolygon/polygon-sdk/pull/296

2022-01-11 18:05 UTC, zivkovicmilos approved these changes
Lookin' good 🚀

2022-01-11 18:34 UTC, brkomir approved these changes

2022-01-16 16:34 UTC, Aleksao998 approved these changes

2022-01-19 10:24 UTC, lazartravica requested changes
Please put the new backup method to the top of the document.

Call the different methods "Backing up blockchain data of a running node" and "Backing up keys" (link to the Vault support, as this is not a good practice).

2022-01-20 04:49 UTC, Kourin1996 commented
@lazartravica Please check my fix at 7b9abbbcf699d73b0171ffc9c51e867e91ce3b22

2022-01-21 08:43 UTC, lazartravica approved these changes

2022-01-21 09:49 UTC, merged