Added new flag for inbound & outbound peer limit
0xPolygon/polygon-edge-docs pull request #48
Opened 2022-01-06 04:19 UTC by munna0908

PSDK-[PR](https://github.com/0xPolygon/polygon-sdk/pull/326)

2022-01-11 18:25 UTC, zivkovicmilos requested changes
Please give a better PR description and re-request a review 👍

2022-01-17 12:15 UTC, Kourin1996 approved these changes

2022-01-19 11:01 UTC, zivkovicmilos requested changes
Please add additional explanations / tips for mutual exclusivity of these inbound / outbound flags and the `max-peers` flag 🙏

2022-01-24 09:28 UTC, zivkovicmilos approved these changes
Lookin' good 💯

2022-01-26 07:13 UTC, lazartravica approved these changes

2022-01-26 07:15 UTC, merged